[package]
name = "cursive_buffered_backend"
version = "0.1.0"
authors = ["Alexander Gavrilov <agavrilov@users.noreply.github.com>"]
license = "MIT"

[dependencies]
smallvec = "0"
unicode-segmentation = "1"
unicode-width = "0"
enumset = "0"
crossbeam-channel = "0"

[dependencies.cursive]
version = "0.10"
default-features = false
features = ["termion-backend"]

[patch.crates-io]
termion = {git = 'https://github.com/agavrilov/termion', branch = 'windows'}
